Data Preprocessing

In [2]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("Dataset/customer_shopping_behavior.csv")
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [6]:
df.shape

(3900, 18)

In [7]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [9]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [10]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [33]:
df['Review_Rating'] = df['Review_Rating'].fillna(3.0)

In [34]:
df.isnull().sum()

Customer_ID               0
Age                       0
Gender                    0
Item_Purchased            0
Category                  0
Purchase_Amount_(USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review_Rating             0
Subscription_Status       0
Shipping_Type             0
Discount_Applied          0
Promo_Code_Used           0
Previous_Purchases        0
Payment_Method            0
Frequency_of_Purchases    0
dtype: int64

In [35]:
df.duplicated().sum()

np.int64(0)

In [36]:
df.dtypes

Customer_ID                 int64
Age                         int64
Gender                        str
Item_Purchased                str
Category                      str
Purchase_Amount_(USD)       int64
Location                      str
Size                          str
Color                         str
Season                        str
Review_Rating             float64
Subscription_Status           str
Shipping_Type                 str
Discount_Applied              str
Promo_Code_Used               str
Previous_Purchases          int64
Payment_Method                str
Frequency_of_Purchases        str
dtype: object

In [37]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace(" ", "_")

In [38]:
df['Gender'].value_counts()

Gender
Male      2652
Female    1248
Name: count, dtype: int64

In [39]:
df['Purchase_Amount_(USD)'].describe()

count    3900.000000
mean       59.764359
std        23.685392
min        20.000000
25%        39.000000
50%        60.000000
75%        81.000000
max       100.000000
Name: Purchase_Amount_(USD), dtype: float64

In [40]:
df.to_csv("cleaned_data.csv", index=False)

Database(MySQL) Connection

In [2]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="7898311594"
)

cursor = conn.cursor()

print("Connected successfully 🚀")

Connected successfully 🚀

In [3]:
cursor.execute("CREATE DATABASE IF NOT EXISTS shopping_db")
print("Database created ✅")

Database created ✅

In [4]:
cursor.execute("USE shopping_db")

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS customers (
    Customer_ID INT,
    Age INT,
    Gender VARCHAR(10),
    Item_Purchased VARCHAR(50),
    Category VARCHAR(50),
    Purchase_Amount FLOAT,
    Location VARCHAR(50),
    Size VARCHAR(10),
    Color VARCHAR(20),
    Season VARCHAR(20),
    Review_Rating FLOAT,
    Subscription_Status VARCHAR(10),
    Shipping_Type VARCHAR(20),
    Discount_Applied VARCHAR(10),
    Promo_Code_Used VARCHAR(10),
    Previous_Purchases INT,
    Payment_Method VARCHAR(20),
    Frequency_of_Purchases VARCHAR(20)
)
""")

print("Table created ✅")

Table created ✅

In [6]:
import pandas as pd

df = pd.read_csv("cleaned_data.csv")

# 🔥 IMPORTANT FIX
df = df.where(pd.notnull(df), None)

for i, row in df.iterrows():
    cursor.execute("""
        INSERT INTO customers (
            Customer_ID, Age, Gender, Item_Purchased, Category,
            Purchase_Amount, Location, Size, Color, Season,
            Review_Rating, Subscription_Status, Shipping_Type,
            Discount_Applied, Promo_Code_Used, Previous_Purchases,
            Payment_Method, Frequency_of_Purchases
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """, tuple(row))

conn.commit()

print("Data inserted ✅")

Data inserted ✅

In [7]:
cursor.execute("SELECT * FROM customers LIMIT 5")

for row in cursor.fetchall():
    print(row)

(1, 55, 'Male', 'Blouse', 'Clothing', 53.0, 'Kentucky', 'L', 'Gray', 'Winter', 3.1, 'Yes', 'Express', 'Yes', 'Yes', 14, 'Venmo', 'Fortnightly')
(2, 19, 'Male', 'Sweater', 'Clothing', 64.0, 'Maine', 'L', 'Maroon', 'Winter', 3.1, 'Yes', 'Express', 'Yes', 'Yes', 2, 'Cash', 'Fortnightly')
(3, 50, 'Male', 'Jeans', 'Clothing', 73.0, 'Massachusetts', 'S', 'Maroon', 'Spring', 3.1, 'Yes', 'Free Shipping', 'Yes', 'Yes', 23, 'Credit Card', 'Weekly')
(4, 21, 'Male', 'Sandals', 'Footwear', 90.0, 'Rhode Island', 'M', 'Maroon', 'Spring', 3.5, 'Yes', 'Next Day Air', 'Yes', 'Yes', 49, 'PayPal', 'Weekly')
(5, 45, 'Male', 'Blouse', 'Clothing', 49.0, 'Oregon', 'M', 'Turquoise', 'Spring', 2.7, 'Yes', 'Free Shipping', 'Yes', 'Yes', 31, 'PayPal', 'Annually')